const accessLogsIndex = {
  max_text_len: 2048,
  log_reduce_white_list: [],
  log_reduce_black_list: [],
  line: {
    chn: false,
    caseSensitive: false,
    token: [",", ".", "\r", "\n"],
  },
  keys: {
    traceId: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "traceId",
      type: "text",
      doc_value: true,
    },
    timestamp: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "timestamp",
      type: "long",
      doc_value: true,
    },
    ipAddress: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "ipAddress",
      type: "text",
      doc_value: true,
    },
    userId: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "userId",
      type: "text",
      doc_value: true,
    },
  },
  index_all: false,
  max_depth: 5,
  json_keys: {},
};
const applicationLogsIndex = {
  max_text_len: 2048,
  log_reduce_white_list: [],
  log_reduce_black_list: [],
  line: {
    chn: false,
    caseSensitive: false,
    token: [",", ".", "\r", "\n"],
  },
  keys: {
    traceId: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "traceId",
      type: "text",
      doc_value: true,
    },
    timestamp: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "timestamp",
      type: "long",
      doc_value: true,
    },
    userId: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "userId",
      type: "text",
      doc_value: true,
    },
    spanId: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "spanId",
      type: "text",
      doc_value: true,
    },
    parentSpanId: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "parentSpanId",
      type: "text",
      doc_value: true,
    },
    eventType: {
      chn: false,
      caseSensitive: false,
      token: ["|"],
      alias: "eventType",
      type: "text",
      doc_value: true,
    },
  },
  index_all: false,
  max_depth: 5,
  json_keys: {},
};

const SLSIndexJson = {
  accessLogs: accessLogsIndex,
  applicationLogs: applicationLogsIndex,
};
export default SLSIndexJson;
